---
title: "BEA Infrastructure Investment"
author: "Alan Jern"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r packages}
library(tidyverse)
library(forcats)
library(ggtext)
library(ggthemes)
library(patchwork)
library(ggrepel)
```


## Read in data
```{r import-data}
investment <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/investment.csv')
chain_investment <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/chain_investment.csv')
ipd <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/ipd.csv')

```

## Explore data
```{r wrangle-data}

top_n_categories <- 4 # Number of categories to include in plot

# Remove the total categories
infrastructure_investments <- chain_investment %>%
  filter(meta_cat != "Total basic infrastructure" &
           meta_cat != "Total infrastructure") %>%
  group_by(meta_cat, year) %>% 
  summarize(inv = sum(gross_inv_chain)) %>%
  filter(year >= 1997) %>% # just show latest 20 years
  mutate(pct_change = (inv - lag(inv, 20)) / lag(inv,20))

biggest_pct_increases <- infrastructure_investments %>%
  ungroup() %>%
  slice_max(order_by = pct_change, n = top_n_categories) %>%
  select(meta_cat)
biggest_pct_decreases <- infrastructure_investments %>%
  ungroup() %>%
  slice_min(order_by = pct_change, n = top_n_categories) %>%
  select(meta_cat)

increase_data <- infrastructure_investments %>% 
  right_join(biggest_pct_increases) %>%
  fill(pct_change, .direction = "up") %>%
  arrange(pct_change, meta_cat, year) %>%
  mutate(label = case_when(
    pct_change > 0 ~ str_c("+", as.character(signif(100*pct_change, digits = 2)), "%"),
    TRUE ~ str_c("-", as.character(signif(100*pct_change, digits = 2)), "%")
    )
  )

decrease_data <- infrastructure_investments %>% 
  right_join(biggest_pct_decreases) %>%
  fill(pct_change, .direction = "up") %>%
  arrange(pct_change, meta_cat, year) %>%
  mutate(label = case_when(
    pct_change > 0 ~ str_c("+", as.character(signif(100*pct_change, digits = 2)), "%"),
    TRUE ~ str_c(as.character(signif(100*pct_change, digits = 2)), "%")
    )
  )

```

## Plot data
```{r plot}

p_increase <- ggplot(data = increase_data,
                     mapping = aes(x = year, y = inv)) +
  geom_line(color = "#084f63",
            size = 1.1,
            show.legend = FALSE, ) +
  geom_label_repel(data = increase_data %>%
                     filter(meta_cat == "Digital" & year == 2017),
                   mapping = aes(x = year, y = inv, label = label),
                   min.segment.length = Inf,
                   nudge_x = -6,
                   size = 2.5) +
  facet_wrap(vars(fct_reorder(meta_cat, pct_change, .desc = TRUE)), 
             nrow = 2, ncol = top_n_categories) +
  scale_y_continuous(breaks = c(0, 50000, 100000, 150000, 200000, 250000), 
                     labels = c("0", "50", "100", "150", "200", "250"),
                     limits = c(0, 255000)) +
  theme_tufte() +
  theme(
    text = element_text(family = "Gill Sans"),
    plot.subtitle = element_markdown(),
    axis.title.y = element_markdown(),
    strip.background = element_rect(color = "white", fill = "gray"),
    plot.background = element_rect(color = "#fefff7", fill = "#fefff7"),
    axis.title.x = element_blank(),
    panel.grid.major.y = element_line(color = "#f5f5f5"),
    plot.title.position = "plot"
  ) +
  labs(
    title = "US infrastructure spending from 1997 to 2017 (adjusted for inflation)",
    subtitle = "Categories with *greatest increases* in spending"
  ) +
  ylab("Billions (USD)")

p_decrease <- ggplot(data = decrease_data,
                     mapping = aes(x = year, y = inv)) +
  geom_line(color = "#ab051e",
            size = 1.1,
            show.legend = FALSE) +
  geom_label_repel(data = decrease_data %>%
                     filter(meta_cat == "Public safety" & year == 2017),
                   mapping = aes(x = year, y = inv, label = label),
                   min.segment.length = Inf,
                   size = 2.5) +
  facet_wrap(vars(fct_reorder(meta_cat, pct_change, .desc = TRUE)), 
             nrow = 2, ncol = top_n_categories) +
  scale_y_continuous(breaks = c(0, 50000, 100000, 150000, 200000, 250000), 
                     labels = c("0", "50", "100", "150", "200", "250"),
                     limits = c(0, 255000)) +
  theme_tufte() +
  theme(
    text = element_text(family = "Gill Sans"),
    plot.subtitle = element_markdown(),
    axis.title.y = element_markdown(),
    strip.background = element_rect(color = "white", fill = "gray"),
    plot.background = element_rect(color = "#fefff7", fill = "#fefff7"),
    axis.title.x = element_blank(),
    panel.grid.major.y = element_line(color = "#f5f5f5"),
    plot.title.position = "plot",
    plot.caption = element_text(color = "gray60")
  ) +
  labs(
    subtitle = "Categories with *greatest decreases* in spending",
    caption = "@alanjern | Data: Bureau of Economic Analysis"
  ) +
  ylab("Billions (USD)")

p_increase / p_decrease

```
```{r print-figure}
if (FALSE) {
  fig.width = 6
  fig.asp = 0.618
  
  ggsave("infrastructure_spending.png", width = fig.width, height = fig.width*fig.asp, units = "in")
}
```

